package com.salestock.didik.model;

// Generated Nov 3, 2017 5:45:10 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShoppingCart generated by hbm2java
 */
@Entity
@Table(name = "shopping_cart")
public class ShoppingCart implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String id;
	private ProductDetail productDetail;
	private OrderTransaction orderTransaction;
	private Product product;
	private int quantity;
	private Date createDate;
	private Date updateDate;
	private String userId;
	
	public ShoppingCart() {
	}

	public ShoppingCart(String id, ProductDetail productDetail, int quantity) {
		this.id = id;
		this.productDetail = productDetail;
		this.quantity = quantity;
	}

	public ShoppingCart(String id, ProductDetail productDetail,
			OrderTransaction orderTransaction, Product product, int quantity,
			Date createDate, Date updateDate) {
		this.id = id;
		this.productDetail = productDetail;
		this.orderTransaction = orderTransaction;
		this.product = product;
		this.quantity = quantity;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_detail_id", nullable = false)
	public ProductDetail getProductDetail() {
		return this.productDetail;
	}

	public void setProductDetail(ProductDetail productDetail) {
		this.productDetail = productDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id")
	public OrderTransaction getOrderTransaction() {
		return this.orderTransaction;
	}

	public void setOrderTransaction(OrderTransaction orderTransaction) {
		this.orderTransaction = orderTransaction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "user_id")
	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
